---
- name: Rotate passwords
  hosts: all

  vars_prompt:
    - name: password
      prompt: Please enter a new password to be used throughout your hosts
      private: yes
      confirm: yes
      salt_size: 8

  tasks:
    - debug:
        msg: "Rotating password for {{ ansible_ssh_user }}"

    - ansible.builtin.user:
        name: "{{ ansible_ssh_user }}"
        password: "{{ password | password_hash('sha512') }}"
      become: yes
